// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXaRktOu_eLxGh8wJhiYs31ZKvFxgCTk',
    appId: '1:701694131737:web:e254ad494dce13ffd3b488',
    messagingSenderId: '701694131737',
    projectId: 'prasadit-ee4a8',
    authDomain: 'prasadit-ee4a8.firebaseapp.com',
    storageBucket: 'prasadit-ee4a8.firebasestorage.app',
    measurementId: 'G-4DJJF6LETK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSnounJsivR2z41wSdcUJ3oYL6jM9U5U',
    appId: '1:701694131737:android:2a5c1eb8989e097cd3b488',
    messagingSenderId: '701694131737',
    projectId: 'prasadit-ee4a8',
    storageBucket: 'prasadit-ee4a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ccrsqXMi_vtLjeD-boTHEgrFHOT_Cj4',
    appId: '1:701694131737:ios:fb279a6f8228bef6d3b488',
    messagingSenderId: '701694131737',
    projectId: 'prasadit-ee4a8',
    storageBucket: 'prasadit-ee4a8.firebasestorage.app',
    iosBundleId: 'com.example.backendFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ccrsqXMi_vtLjeD-boTHEgrFHOT_Cj4',
    appId: '1:701694131737:ios:fb279a6f8228bef6d3b488',
    messagingSenderId: '701694131737',
    projectId: 'prasadit-ee4a8',
    storageBucket: 'prasadit-ee4a8.firebasestorage.app',
    iosBundleId: 'com.example.backendFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjXaRktOu_eLxGh8wJhiYs31ZKvFxgCTk',
    appId: '1:701694131737:web:9966209b662fbba5d3b488',
    messagingSenderId: '701694131737',
    projectId: 'prasadit-ee4a8',
    authDomain: 'prasadit-ee4a8.firebaseapp.com',
    storageBucket: 'prasadit-ee4a8.firebasestorage.app',
    measurementId: 'G-3QKDBHQ2SK',
  );
}
